unzip:
	find . -name "*gz"| xargs -n1 gunzip	

copy:
	cp -v /TEACHING/BIOINF21/data/reference_fasta/chr21.fa.gz* data/reference_fasta/
	cp -v /TEACHING/BIOINF21/data/reference_fasta_hs37d5/chr1.fa.gz* data/reference_fasta_hs37d5/
